### ISSUE TITLE
Can't use other textures than the softbox

### ISSUE THREAD

**Issue by michelchafouin** [leomoon-studios/leomoon-lightstudio#2] opened 2017-02-12 17:25 UTC
Changing the textures for a light, but it keeps using the Softbox texture.

Just downloaded the latest version, I followed the install instructions, the folder with the textures has been copied to the addons folder.

**Comment by theres1** [comment] 2017-02-12 18:28
What Blender version and OS are you using?
Can you provide exact steps to reproduce your issue? Did you use custom textures or edit material nodes?

**Comment by michelchafouin** [comment] 2017-02-12 19:07
I'm on Windows 10, I tried the addon using Blender 2.78a and 2.78b.

I am trying to use the textures that are provided with the addon.
I downloaded the addon from github, extracted and installed the zip containing the addon.
Activated the addon in Blender user preferences.
Then I created a light studio, added a light.
I'm clicking on the texture image in the Tool panel to replace the softbox with another one, but nothing happens. The image changes in the Tool Panel, but it doesn't get applied to the light material.

I haven't touched material nodes.

I do get some shortcuts issues because of my selection setup (maya-like), but I doubt this is related to the texture assignment.

Thanks for the support.

**Comment by theres1** [comment] 2017-02-12 22:16
Do you see any errors in console (Window -> Toggle System Console)?
Does the image in Tool panel revert back to softbox after you change it?

Please try these steps:
1. Delete blender-light-studio directory from both C:\Users\<you>\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\ and <Blender installation path>\2.78\scripts\addons\
2.  Install addon manualy: unpack zip file (from 'build' directory) directly to C:\Users\<you>\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\

Did it work?

Try to load one of the default textures directly in material nodes. Does it change image in Tool panel too?

**Comment by michelchafouin** [comment] 2017-02-13 18:03
Tried reinstalling and it didn't work.
I actually get it to work as expected BEFORE clicking on Prepare Layout, or opening the node editor.
The textures are not listed in the material nodes, there is only Soft Box A.exr.001 there, and it stays the same even if I have changed the textures previously.

It is super weird.
The console doesn't say much. It prints Set preview = (number of the texture) but nothing else.

I tried with a clean install of Blender and it works. Not sure what's going on in the settings that would mess up with that. I'll progressively remove keymaps, startup file, addons, to find the culprit.

**Comment by theres1** [comment] 2017-02-13 18:20
Ok, that would be helpful info. Anyway, good to know it works with clean install.

**Comment by michelchafouin** [comment] 2017-02-17 21:46
It's because of my startup file, but I don't know what can cause this. In case you are interested in reproducing it, here is the file: http://pasteall.org/blend/index.php?id=45602

**Comment by theres1** [comment] 2017-02-17 23:41
Issue was caused by auto-packing feature. I pushed fix to dev branch.

**Closed as completed by theres1** 2017-02-17 23:41 UTC
